path_folder_out: '../output/20200119_focal_mask_v2'

model:
  input_width: 1536
  input_height: 512 # IMG_HEIGHT = IMG_WIDTH // 16 * 5
  factor_downsample: 4
  num_classes: 8 # x,y,z, yaw, pitch_cos, pitch_sin, roll, confidence
  path_weights: '../output/20200112_focal_loss_v2/model_5.pth'
  flag_use_dummy_model: 0

datasets:
  flag_use_mask: 1
  train:
    path_csv: '../data/train_train.csv'
    path_folder_images: '../data/train_images'
    path_folder_masks: '../data/train_masks'
  valid:
    path_csv: '../data/train_valid.csv'
    path_folder_images: '../data/train_images'
    path_folder_masks: '../data/train_masks'
  test:
    path_csv: '../data/sample_submission.csv'
    path_folder_images: '../data/test_images'
    path_folder_masks: '../data/test_masks'

mode: 'train' # train or predict

train:
  use_augmentation: 0
  batch_size: 4
  batch_size_eval: 4
  num_epochs: 10
  learning_rate:
    initial: 0.002
    num_epochs_const: 30 # thus effectively disable LR decay
    factor_decrease: 0.1
  loss:
    flag_focal_loss: 1
    flag_size_average: 1

predict:
  batch_size: 1
  num_batches_max: 99999999
  flag_optimize: 1 # modify x,y,z using predicted u,v and y(x,z) fit
  flag_plot_mat: 1
  flag_plot_item: 1
