model:
  input_width: 1024
  input_height: 320 # IMG_HEIGHT = IMG_WIDTH // 16 * 5
  factor_downsample: 8
  num_classes: 8 # x,y,z, yaw, pitch_cos, pitch_sin, roll, confidence
  path_weights: 'output/model_11.pth'


dataset:
  path_csv: '/kaggle/input/pku-autonomous-driving/train.csv'
  path_folder_images: '/kaggle/input/pku-autonomous-driving/train_images'
  path_folder_masks: '/kaggle/input/pku-autonomous-driving/train_masks'

mode: 'predict' # train or predict

train:
  batch_size: 2
  num_epochs: 10
  idx_epoch_switch: 0
  learning_rate: 0.001
  path_csv_out: 'out_train.csv'

predict:
  batch_size: 1
  num_batches_max: 2
  flag_plot_output: 0
  flag_plot_item: 0
  path_csv_out: 'out_predict.csv'

