path_folder_out: '../output/20200121_focalnew_mask/model_10'

model:
  input_width: 1536
  input_height: 512 # IMG_HEIGHT = IMG_WIDTH // 16 * 5
  factor_downsample: 4
  num_classes: 8 # x,y,z, yaw, pitch_cos, pitch_sin, roll, confidence
  path_weights: '../output/20200121_focalnew_mask/model_10.pth' #'model.pth' # = '../output/20200112_focal_loss_v2/model_6.pth'
  flag_use_dummy_model: 0

datasets:
  flag_use_mask: 1
  train:
    path_csv: 'csv/train_train.csv'
    path_folder_images: '/kaggle/input/pku-autonomous-driving/train_images'
    path_folder_masks: '/kaggle/input/pku-autonomous-driving/train_masks'
  valid:
    path_csv: 'csv/train_valid.csv'
    path_folder_images: '/kaggle/input/pku-autonomous-driving/train_images'
    path_folder_masks: '/kaggle/input/pku-autonomous-driving/train_masks'
  test:
    path_csv: '/kaggle/input/pku-autonomous-driving/sample_submission.csv'
    path_folder_images: '/kaggle/input/pku-autonomous-driving/test_images'
    path_folder_masks: '/kaggle/input/pku-autonomous-driving/test_masks'

mode: 'predict' # train or predict

train:
  use_augmentation: 0
  batch_size: 2
  batch_size_eval: 8
  num_epochs: 15
  learning_rate:
    initial: 0.002
    num_epochs_const: 30
    factor_decrease: 0.2
  loss:
    flag_focal_loss: 1
    flag_size_average: 1

predict:
  batch_size: 1
  num_batches_max: 99999999
  flag_optimize: 1 # modify x,y,z using predicted u,v and y(x,z) fit
  flag_plot_mat: 0
  flag_plot_item: 0



